[workspace]
resolver = "2"
members = ["spell-framework", "spell-cli", "spell-demo"]

# [patch.crates-io]
# slint = { git = "https://github.com/slint-ui/slint" }
# slint-build = { git = "https://github.com/slint-ui/slint" }
# i-slint-core = { git = "https://github.com/slint-ui/slint" }
# i-slint-renderer-skia = { git = "https://github.com/slint-ui/slint" }
[patch.crates-io]
slint = { git = "https://github.com/slint-ui/slint", rev = "fca8dcbacf79ce75c6e353fdfff58849f3566c89" }
slint-build = { git = "https://github.com/slint-ui/slint", rev = "fca8dcbacf79ce75c6e353fdfff58849f3566c89" }
i-slint-core = { git = "https://github.com/slint-ui/slint", rev = "fca8dcbacf79ce75c6e353fdfff58849f3566c89" }
i-slint-renderer-skia = { git = "https://github.com/slint-ui/slint", rev = "fca8dcbacf79ce75c6e353fdfff58849f3566c89" }
